# flake8: noqa

"""
    test

    test  # noqa: E501

    The version of the OpenAPI document: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from testopenapi.api_client import ApiClient

# import Configuration
from testopenapi.configuration import Configuration

# import exceptions
from testopenapi.exceptions import OpenApiException
from testopenapi.exceptions import ApiAttributeError
from testopenapi.exceptions import ApiTypeError
from testopenapi.exceptions import ApiValueError
from testopenapi.exceptions import ApiKeyError
from testopenapi.exceptions import ApiException
