"""
    test

    test  # noqa: E501

    The version of the OpenAPI document: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "testopenapi"
VERSION = "1.0.0"
