"""
    test

    test  # noqa: E501

    The version of the OpenAPI document: 1.0.1-1
    Contact: pv.safronov@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testopenapi
from testopenapi.model.test import Test


class TestTest(unittest.TestCase):
    """Test unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTest(self):
        """Test Test"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Test()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
